### ISSUE TITLE
[SUGGESTION] Eldritch Gown

### ISSUE THREAD

**Issue by srnyx** [PheonixVX/fof#4]
**It'd be cool if you made it so the Eldritch Gowns were sort of like Weeping Angels from Doctor Who.**

When the player isn't looking at them, they will move closer to the player, but not extremely fast.
When the player is looking at them, they won't move at all.
If the angel reaches the player, it will teleport the player to maybe the Nether or just some random coordinates (changing the y to like 60 or something so the player has a lesser chance of suffocating or dying from fall damage).
_I'm not entirely sure how the Doctor Who weeping angels work, all I know is that they move when the person isn't looking at them._

**Comment by PhoenixVX** [comment]
While I do encourage suggestions, please elaborate when making them. Such as, "because their unique nature necessitated that they often covered their faces with their hands to prevent trapping each other in petrified form for eternity by looking at one another. " which I borrowed from a wiki on the Weeping Angel.

**Comment by srnyx** [comment]
> While I do encourage suggestions, please elaborate when making them.

Edited my description, will keep what you said in mind for the future!

**Comment by PhoenixVX** [comment]
My artist/mod helper has decided that this issue should be closed. While I do appreciate the idea of yours, I will save it either for later or for a different mod. Thanks for understanding :).
